### ISSUE TITLE
Bug: Send output to the correct stream

### ISSUE THREAD

**Issue by ac10n** [pinnacle-labs/taqueria#1088]
MVP:
- Docker dowload output is filtered
- Centralized place for regex definitions (to be expanded upon)

The CLI can sometimes send normal output to the `standard error` stream.
This is not a problem for the CLI users in normal interactive terminal usage.

But the TVsCE can interpret these as real warnings.

**Comment by AlirezaHaghshenas** [comment]
As the following code shows, the normal output is sent to error.

```
➜  ECAD mkdir sample3
➜  ECAD cd sample3
➜  sample3 taq scaffold https://github.com/ecadlabs/taqueria-scaffold-demo 2 > error.txt
Cloning into '/Users/alireza/work/ECAD/sample3/2'...
➜  sample3 cat error.txt

 Scaffolding 🛠
 into: /Users/alireza/work/ECAD/sample3/2
 from: https://github.com/ecadlabs/taqueria-scaffold-demo...
```

**Comment by hu3man** [comment]
@AlirezaHaghshenas, please add any additional context or examples that you have

**Comment by hu3man** [comment]
@AlirezaHaghshenas, please add any additional context or examples that you have

**Comment by AlirezaHaghshenas** [comment]
When the CLI sends any text to standard error, TVsCE interprets that as warning (if the program succeeds) or as error (if it fails). 
In some cases, the CLI sends normal output to standard error instead of standard output. On the CLI, this is not a problem (and not even detectable, as both outputs are shown by the terminal).

However, if people try piping output and error to different programs, this will start causing them problems.

**Comment by hu3man** [comment]
@jchenche, is this something that you could take on as part of the work in [🐛 Bug ➾ some outputs from LIGO test results are piped to stdout, which we don't capture now#1288](https://github.com/ecadlabs/taqueria/issues/1288)?

**Comment by jchenche** [comment]
> @jchenche, is this something that you could take on as part of the work in [🐛 Bug ➾ some outputs from LIGO test results are piped to stdout, which we don't capture now#1288](https://github.com/ecadlabs/taqueria/issues/1288)?

This is unrelated to the LIGO test results bug.

**Comment by jchenche** [comment]
@hu3man this is a build process issue. Due to the fact that we invoke `taq` as part of the build-all process, no outputs can be piped to stdout from the CLI I believe.

**Comment by jchenche** [comment]
@hu3man No outputs can be piped to stdout from the plugins either, but this one is due to the plugin architecture's limitation which my architecture improvement suggestion will solve.

**Comment by hu3man** [comment]
Oh right, I do remember you explaining this before. We'll consider it blocked for now

**Comment by mweichert** [comment]
Fixed
