### ISSUE TITLE
💭 Idea ➾ An abilty to use local compiler instead of dockerized version

### ISSUE THREAD

**Issue by sinapsist** [pinnacle-labs/taqueria#1219]
### 🔮 Title / Topic

UX Improvment

### 💭 Details

Currently, we provide only an option to use dockerized version. But sometimes user has smartpy or ligo cli already installed.
It would be nice to provide an option for users to use a local version of installed smartpy or ligo cli.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Done, other than SmartPy which internally uses Docker.
