### ISSUE TITLE
🚧 Dev ➾ Add Support for Versioned Documentation to Taqueria.io

### ISSUE THREAD

**Issue by hu3man** [pinnacle-labs/taqueria#1335]
### 🚥 Definition of Done

- [X] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation (PR merged)
- [ ] ✍️ Release Notes Added
- [ ] 🏆 Product Acceptance

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] A menu bar drop down shows the historical, current, and next versions of Taqueria
- [ ] Clicking on a particular version will show documentation versioned to that release
- [ ] Clear and concise instructions for adding a new release  are documented in the readme.md file 
- [ ] Must support staging of unreleased docs (ie PR with docs merged, but no release has gone out yet) which get published as current as part of the release process

 📐 Non-Functional: 
- [ ] Maintenance burden should be minimized 
 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- Backfilling docs for versions previous to the feature launch version
 
 

### 🧰 Work Description

Taqueria is now releasing incremental features at a rapid rate. As such, documentation can change significantly between releases and it's increasingly important to have a way to version docs to match with releases. This ticket covers the work involved to implement versioned docusaurus docs in the same manner handled on tezostaquito.com

### 🦄 Sizing

5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
@dsawali, Jev mentioned that you implemented this for the Taquito site and was hoping you could share some knowledge or even give us a hand with it

**Comment by dsawali** [comment]
Hello @hu3man, I would be glad to help the Taqueria team. 

I assume that the Taqueria website also uses Docusaurus, since that is what we use to implement versioned docs in Taquito.
To start, I would suggest going over this documentation https://docusaurus.io/docs/versioning. It has most of the things we'd need, but I would be glad to help out if needed. 

Let me know the team's bandwidth (or lack thereof) so we could adjust who would be driving most of the change

**Comment by dsawali** [comment]
Luckily I find this is one of those things that is pretty straightforward in Docusaurus. If you have any questions, please don't hesitate to reach out again! @hu3man

**Comment by hu3man** [comment]
Awesome, thanks @dsawali!
