### ISSUE TITLE
 🐛 Bug ➾ Rename to @taqueria/plugin-tezos-client  to @taqueria/plugin-octez-client

### ISSUE THREAD

**Issue by michaelkernaghan** [pinnacle-labs/taqueria#1481]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

tezos-client was renamed octez-client

### 🆘 Steps to Reproduce?

Look at the plugin list in the docs. 
The name tezos-client should be octez client throughout.

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

everytime

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.23.6-rc.1

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Done
