### ISSUE TITLE
💭 Idea ➾ Create `artifacts` directory if not present

### ISSUE THREAD

**Issue by egarson** [pinnacle-labs/taqueria#1523]
### 🔮 Title / Topic

Create `artifacts` directory if not already present

### 💭 Details

If I do a `taq compile` and no `artifacts` directory is present, taqueria appears to hang ("appears" because if you wait long enough - a few minutes in my case - the prompt returns).
You might reasonably ask why the `artifacts` directory would not be present. In my case, I pulled an existing taqueria project onto another machine and only got the `contracts` directory, because git won't create empty directories on pull and I didn't commit my compiled ligo files.
This is pretty minor, but the fix should be easy: a quick check that `artifacts` exists so no "internal error" is emitted on `taq compile` - just silently create it. This might save some head scratching.
Cheers

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Fixed
