### ISSUE TITLE
🐛 Bug ➾ the test contract increment.jsligo in test/e2e/data has 'let' but should be 'const'

### ISSUE THREAD

**Issue by michaelkernaghan** [pinnacle-labs/taqueria#1607]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Trying to update an automated test and was getting an error from the taq compile for this test contract. The error is not getting caught in the tests, but it is discoverable manually.

### 🆘 Steps to Reproduce?

1. taq init project-foo
2. cd project-foo
3.   taq install @taqueria/plugin-ligo
4.  cd contracts
5.  touch increment.jsligo
6.  copy taqueria/tests/e2e/data/increment.jsligo  >>  increment.jsligo
7.  taq add-contract increment.jsligo
8. 
```
┌──────────────────┬──────────────────┬─────────────────┐
    │ Name             │ Source File      │ Last Known Hash │
   ├──────────────────┼──────────────────┼─────────────────┤
   │ increment.jsligo │ increment.jsligo │ 3254d3d5        │
   └──────────────────┴──────────────────┴─────────────────┘
```
10.  taq compile --plugin ligo increment.jsligo
11.  File "contracts/increment.jsligo", line 16, character 4 to line 24, character 5:
 15 |        the smart contract parameter. */
 16 |     let main = ([action, store] : [parameter, storage]) : return_ => {
 17 |      return [
 18 |        (list([]) as list <operation>),    // No operations
 19 |        (match (action, {
 20 |         Increment: (n: int) => add ([store, n]),
 21 |         Decrement: (n: int) => sub ([store, n]),
 22 |         Reset:     ()  => 0}))
 23 |       ]
 24 |     };

Toplevel let declaration are silently change to const declaration.

File "contracts/increment.jsligo", line 12, characters 4-74:
 11 |     let add = ([store, delta] : [storage, int]) : storage => store + delta;
 12 |     let sub = ([store, delta] : [storage, int]) : storage => store - delta;
 13 |     

Toplevel let declaration are silently change to const declaration.

File "contracts/increment.jsligo", line 11, characters 4-74:
 10 |     /* Two entrypoints */
 11 |     let add = ([store, delta] : [storage, int]) : storage => store + delta;
 12 |     let sub = ([store, delta] : [storage, int]) : storage => store - delta;

Toplevel let declaration are silently change to const declaration.

Note: storage file associated with "increment.jsligo" can't be found, so "increment.storageList.jsligo" has been created for you. Use this file to define all initial storage values for this contract

Note: parameter file associated with "increment.jsligo" can't be found, so "increment.parameterList.jsligo" has been created for you. Use this file to define all parameter values for this contract
┌──────────────────┬────────────────────────┐
│ Contract         │ Artifact               │
├──────────────────┼────────────────────────┤
│ increment.jsligo │ artifacts/increment.tz │
└──────────────────┴────────────────────────┘1
```
10. it creates the artifact anyway, but its got errors
12.  change increment.jsligo to have const instead of let
13.  re do the taq compile --plugin ligo increment.jsligo and it works 
```
┌────────────────────────────────┬────────────────────────┐
│ Contract                       │ Artifact               │
├────────────────────────────────┼────────────────────────┤
│ increment.jsligo               │ artifacts/increment.tz │
├────────────────────────────────┼────────────────────────┤
│ increment.storageList.jsligo   │                        │
├────────────────────────────────┼────────────────────────┤
│ increment.parameterList.jsligo │                        │
└────────────────────────────────┴────────────────────────┘
```
14. after making this change, run the existing e2e tests t see if there are any breaks because of the changed data file.
15.  there are not, but note the change in the file will change the hash of the file.


### 🪵 Relevant log output

_No response_

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

_No response_

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.23.24

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Fixed
