### ISSUE TITLE
🐛 Bug ➾ archetype plugin compile fails if more than one contract in dir

### ISSUE THREAD

**Issue by michaelkernaghan** [pinnacle-labs/taqueria#1678]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Trying to get archetype to compile more than one contract in the contract directory using the command to compile without specifying the file name in the parameter. It does not work.

The task of adding contracts (add-contract) to the contract directory, which may be necessary to get the compile to work without parameters, needs to be fixed.

### 🆘 Steps to Reproduce?

load the archetype plugin
1.  put a valid .arl contract into the contract directory
2. call taq compile
3. error that no contracts were found
4. try add-contract first
5. add-contract odes not add a contract to the contract dir.

### 🪵 Relevant log output

```shell
console.log
    [
      '┌────────────┬──────────┐',
      '│ Contract   │ Artifact │',
      '├────────────┼──────────┤',
      '│ None found │ N/A      │',
      '└────────────┴──────────┘'
    ]
```

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

if they try to compile multiple files with archetype

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.25.19-rc

### 🌿 Node.js Version

v16.19

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Fixed
