### ISSUE TITLE
🚧 Dev ➾ Add test to check if TzKt is functioning properly

### ISSUE THREAD

**Issue by ac10n** [pinnacle-labs/taqueria#1696]
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

Any change in the Flextesa sandbox can cause TzKt to fail. Last time it failed because of some new features in the Flextesa image that were not yet supported by the TzKt image we were using.

### ✅ To Do

- [ ] Implement test(s) that verify TzKt functionality

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] Test(s) only pass if TzKt.syn successfully saves data to PostgreSQL and TzKt.api successfully serves them

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Done
