### ISSUE TITLE
🐛 Bug ➾ Amount shown in table after `taq fund` is using incorrect unit type

### ISSUE THREAD

**Issue by mweichert** [pinnacle-labs/taqueria#1823]
### 🚥 Status (Internal Taqueria Team Use Only)

- [X] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Using the steps below, the following table is displayed:

```
┌───────────────┬──────────────────────────────────────┬──────────────┐
│ Account Alias │ Account Address                      │ Mutez Funded │
├───────────────┼──────────────────────────────────────┼──────────────┤
│ bob           │ tz1MVQAjKr2Y9SDCTJkoZwiWGfXjSmsCz6h2 │ 3            │
├───────────────┼──────────────────────────────────────┼──────────────┤
│ alice         │ tz1QqQy27r58bFUcV9E6cGnM3jH9fKh82HP4 │ 3            │
├───────────────┼──────────────────────────────────────┼──────────────┤
│ john          │ tz1fJybRUg5mwWmH6rpTay1aD1Y5jMyHjcFH │ 3            │
├───────────────┼──────────────────────────────────────┼──────────────┤
│ jane          │ tz1P5STNMLjHPYHbitR3qNpJu11eUkANyT4y │ 3            │
├───────────────┼──────────────────────────────────────┼──────────────┤
│ joe           │ tz1fNUMyV1B7uMGyine9Z2LTvNaNaXi2ibn4 │ 3            │
└───────────────┴──────────────────────────────────────┴──────────────┘
```
Notice how the amount of Mutez displayed for each account is `3` whereas it should be `3,000,000`.

### 🆘 Steps to Reproduce?

Using the `0.27.16-rc` prerelease:

1. Initialize a new project: `taq init test-project`
2. Navigate to the project: `cd test-project`
3. Set the environment to testing: `taq set-environment testing`.
4. Install the taquito plugin: `taq install @taqueria/plugin-taquito@next`
5. Run `taq instantiate-account`
6. Run `taq fund`. Follow the instructions to fund the account via faucet.
7. Run `taq fund` to fund all instantiated accounts to their declared balances (3,000,000).
8. Notice that the Mutez is 3 in the table output

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

Each time you run `taq fund`

### 💻 Operating System

MacOS

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.27.16-rc

### 🌿 Node.js Version

v16.16.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment]
I confirmed this happens.

**Comment by jchenche** [comment]
If config shows "3_000_000" it might just interpret it as 3. Try using "3000000" or 3000000
