### ISSUE TITLE
💭 Idea ➾ Update Typescript to v5.0

### ISSUE THREAD

**Issue by BearCooder** [pinnacle-labs/taqueria#1853]
### 🔮 Title / Topic

Update Typescript to v5.0

### 💭 Details

Typescript 5.0 just got released with lots of improvements. So it might be worth to update to v5.

Here is the announcement:
https://twitter.com/typescript/status/1636416665071288321

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Done
