### ISSUE TITLE
🐛 Bug ➾ optional parameter on entrypoint not correctly generated by Taqueria makes Typescript wrong

### ISSUE THREAD

**Issue by zamrokk** [pinnacle-labs/taqueria#1861]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

![image](https://user-images.githubusercontent.com/2536368/229447994-70719903-cecf-40e1-8c20-9c49f105ac5f.png)

My entrypoint contains an optional, when I run the taqueria type generation it creates the fields in random postiion, so my optional field here appear on first position. On Typescript, we should list all mandatory fields first 

Here the parameter in jsligo from the smart contract :

`export type removeMemberRequest = {
    member : address, 
    orgName : string,
    lastAdmin : option<address>
};`

Here the portion of the file generated by Taqueria

`type Methods = {
    removeMember: (
        lastAdmin?: address,
        member: address,
        orgName: string,
    ) => Promise<void>;
  ...  
    `

### 🆘 Steps to Reproduce?

add on optionla field on an entrypoint parameter and generate the type via taqueria plugin

### 🐘 How impactful is this bug?

🤔 Notable but managable

### 💻 Operating System

None

### 🕸️ System Architecture

None

### 🌮 Taqueria Version

v0.28.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zamrokk** [comment]
asking ligo team about WHO is deciding (alphabetic) field ordering in Michelson ...

![image](https://user-images.githubusercontent.com/2536368/231522236-87db86cd-c75c-4f8c-9828-06d82c247c91.png)

**Comment by zamrokk** [comment]
Ok, I found a woraround, maybe it is also the way to fix it quickly

Keep same order, but change how Typescript generate the type definition

Do this

`    lastAdmin: address | undefined,`

Instead of 

`    lastAdmin?: address,`

@mweichert @michaelkernaghan 

Can you do this fix ? 
I tried with taquito passing undefined and an address and both seems ok for the node

On tzkt indexer, it says when `undefined `is passed that the value on storage is `null`, so I suppose is the representation of `None()`

**Comment by zamrokk** [comment]
I saw you choose the reorder the fields, I am not sure it is working as Michelson contract field ordering has to be the same on the node side ...
You should do a test calling a contract 

I would recommend replace `myfield?` by `myField | null`

**Comment by zamrokk** [comment]
@michaelkernaghan @mweichert For me the bug is still here. We should reopen this ticket as I need to manually process all generated files

I recommend to fix this with ` myField | null`   instead of `myField?`

**Comment by mweichert** [comment]
OK, thanks for the additional feedback, @zamrokk. I had tested this but perhaps the contract I was using was not sufficient for this case. 

Btw, Michael K and others from the ECAD Labs team are no longer working on Taqueria.

**Comment by mweichert** [comment]
https://github.com/ecadlabs/taquito/issues/2344
