### ISSUE TITLE
🌋 E|F ➾ allow to set the default storage naming a bit better

### ISSUE THREAD

**Issue by zamrokk** [pinnacle-labs/taqueria#1872]
### 🚥 Status

- [ ] 🔮 Product/Feature Design
- [ ] ✍🏻 Architecture/Implementation Planning
- [ ] 🏗️ Under Construction
- [ ] ⛳ Feature Complete
- [ ] ⛵ GTM / Release

### 📐 Feature Description

Today the first declaration of variable in storage.jsligo files will be converted to "default_storage" output artifact.

I would like to define all my environment variables and then set the defaut to what I want : Ex : 

`const ghostnet = {...};
const mainnet = {...};
const default_storage = ghostnet;
`

This is not possible to do this today, the output will be 

`
main.storageList.jsligo   │ artifacts/main.default_storage.tz         │
│                           │ artifacts/main.storage.mainnet.tz         │
│                           │ artifacts/main.storage.default_storage.tz
`

and I want 

`
 main.storageList.jsligo   │ artifacts/main.default_storage.tz  │
│                           │ artifacts/main.storage.mainnet.tz  │
│                           │ artifacts/main.storage.ghostnet.tz
`

### 🚩 Problem or Use Case

It is to have something dynamic on the CI pipeline based on the target environment

### ⚖️ Acceptance Criteria

✨ Features: 
- [ ] ... 
 
 📚 Docs: 
- [ ] ... 

### 🔭 Scope

🏎️ In Scope: 
- ... 
 
 🙅‍♂️ Out of Scope: 
- ... 
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by callistonianembrace** [comment]
I have attempted a fix for this in [this PR](https://github.com/pinnacle-labs/taqueria/pull/1923) 

Basic idea behind the PR is to ask users to explicitly set a variable `default_storage` which would be considered so, instead of the earlier guess that first declaration is the default value.
