### ISSUE TITLE
Entrypoints not found when compiling parameters using LIGO

### ISSUE THREAD

**Issue by mweichert** [pinnacle-labs/taqueria#1885]
I am using v0.28.6 and I still have an issue using the parameter file

![image](https://github.com/ecadlabs/taqueria/assets/2536368/966b29ba-bc92-4b27-a6a7-9943c45c9d49)

It is no more a `main` function missing but it cannot see my contract entrypoints (I checked all other entrypoints, it is the same issue ...)

Like you can see, if I compile with ligo CLI v0.65.0, the parameter is compiled correctly, but if I use taqueria on same ligo version 0.65.0, then it fails  

cmd : `TAQ_LIGO_IMAGE=ligolang/ligo:0.65.0 taq compile pokeGame.jsligo`

error : `Constructor "UpdateFeedbackFunction" not found. `

You can reproduce this running the training dapp-4 here : https://github.com/marigold-dev/training-dapp-4
Section `stored lambda function` , just before doing the `taq call ...`

_Originally posted by @zamrokk in https://github.com/pinnacle-labs/taqueria/issues/1867#issuecomment-1557407621_

**Comment by zamrokk** [comment]
Hi @mweichert , I have still the bug on Taqueria V0.37

Any news on this ?

**Comment by mweichert** [comment]
Hi @zamrokk I'm investigating this one. From my perspective, the way we're invoking LIGO is an intuitive expectation and use-case. I need to discuss the issue with their team and then decide how to resolve, based on whether they think this could be a problem on their end or not.

**Comment by mweichert** [comment]
This issue is bigger than initially thought. There are essentially 4 different forms a smart contract can have in LIGO

### 1) Smart contract defined in a file with a main function but NOT wrapped in a module/namespace

This is the legacy way of authoring a smart contract:
```
type storage = int

type parameter =
  Increment of int
| Decrement of int
| Reset

type return = operation list * storage

// Two entrypoints
let add (store, delta : storage * int) : storage = store + delta
let sub (store, delta : storage * int) : storage = store - delta

(* Main access point that dispatches to the entrypoints according to
   the smart contract parameter. *)

let main (action, store : parameter * storage) : return =
 ([] : operation list),    // No operations
 (match action with
   Increment (n) -> add (store, n)
 | Decrement (n) -> sub (store, n)
 | Reset         -> 0)
```

### 2) Smart contract defined in a file with a main function but IS wrapped in a module/namespace

This seems the most rare form:
```
module Counter = struct
  type storage = int

  type parameter =
    Increment of int
  | Decrement of int
  | Reset

  type return = operation list * storage

  // Two entrypoints

  let add (store, delta : storage * int) : storage = store + delta
  let sub (store, delta : storage * int) : storage = store - delta

  (* Main access point that dispatches to the entrypoints according to
    the smart contract parameter. *)

  let main (action, store : parameter * storage) : return =
  ([] : operation list),    // No operations
  (match action with
    Increment (n) -> add (store, n)
  | Decrement (n) -> sub (store, n)
  | Reset         -> 0)
end
```

### 3) Smart contract defined in a file with a function annotated using `@entry`  but NOT wrapped in a module/namespace

This seems the most popular form:
```
  export type storage = int;
  type ret = [list<operation>, storage];

  // Three entrypoints

  @entry
  const increment = (delta : int, store : storage) : ret =>
    [list([]), store + delta];

  @entry
  const decrement = (delta : int, store : storage) : ret =>
    [list([]), store - delta];

  @entry
  const reset = (_ : unit, _ : storage) : ret =>
    [list([]), 0];
```

### 4) Smart contract defined in a file with a function annotated using `@entry`  but IS wrapped in a module/namespace

This is the recommended approach by the LIGO team thus far:
```
module Counter = struct
  [@entry] let increment (p : int) (s : int) : operation list * int = [], s + p
  [@entry] let decrement (p : int) (s : int) : operation list * int = [], s - p
  [@entry] let reset (_: unit) (_: int) : operation list * int = [], 0
end
```

Lastly, a source file can include multiple smart contracts:
```
module Increment = struct
  [@entry] let increment (p : int) (s : int) : operation list * int = [], s + p
  [@entry] let decrement (p : int) (s : int) : operation list * int = [], s - p
end

module HelloWorld = struct
  [@entry] let getName (_: unit) (s: string) : operation list * string = [], s
  [@entry] let setName (name: string) (_: string) : operation list * string = [], name
end
```

Each of these forms has different compiler flags required, not just for compiling the contract, but for compiling the parameterList and storageList files as well.

Additionally, when we generate a parameterList and storageList files, we're using the `#include` directive which is somewhat frowned upon as a default choice for referencing a file.

We've decided to resolve this by:
- Our LIGO plugin compile/compile-all tasks will detect smart contracts (using logic described here: https://github.com/pinnacle-labs/taqueria/discussions/1894)
- Our LIGO compile/compile-all tasks will automatically determine which flags to pass to the ligo compiler for contracts as well as parameterList and storageList files
- We'll add a `-m` flag to the compile task to specify what specific module you'd like to compile. Useful if there are multiple smart contracts defined in your source file.
- Generated parameterList and storageList files will import contracts using the `#import` directive and call the module `Contract`. The examples will be tailored to the detected smart contract form.
