### ISSUE TITLE
🐛 Bug ➾ option contained inside storage structure is not converted to Some or null

### ISSUE THREAD

**Issue by zamrokk** [pinnacle-labs/taqueria#1895]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I have this Structure in ligo 

```
type board = map<round, option<player> >;

export type t = {
    total_rounds : nat,
    players : list<player>,
    current_round : nat,
    rounds : rounds<bytes>,
    decoded_rounds : rounds<action>,
    board : board,
    result : result,
    asleep : timestamp,
    pool : tez     //bet pool in tez. 1 tez / round play movement
};
```

Look at the board type, it has a map of optional, then when I generate the types 
```
taq generate types ./app/src
```

I get 
```
export type Storage = {
  metadata: BigMap<string, bytes>;
  next_session: nat;
  sessions: MMap<
    nat,
    {
      asleep: timestamp;
      board: MMap<nat, address>;
      current_round: nat;
      decoded_rounds: MMap<
```

but I expect
```
export type Storage = {
  metadata: BigMap<string, bytes>;
  next_session: nat;
  sessions: MMap<
    nat,
    {
      asleep: timestamp;
      board: MMap<nat, { Some: address } | null>;
      current_round: nat;
      decoded_rounds: MMap<
```

I have taq v0.37.0

### 🆘 Steps to Reproduce?

reproduce a similar structure and generate the types for typescript

### 🐘 How impactful is this bug?

None

### 💻 Operating System

Windows -> WSL

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.37.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
@zamrokk when you get some time, do you mind uploading the michelson contract for this? Thanks!

**Comment by zamrokk** [comment]
@mweichert , sure

It is the mobile game training here => https://github.com/dvkam/training-dapp-shifumi/tree/main/solution
