### ISSUE TITLE
🌋 E|F ➾ Export all type-aliases.ts functions so we can use it to initialise MMaps

### ISSUE THREAD

**Issue by zamrokk** [pinnacle-labs/taqueria#1902]
### 🚥 Status

- [ ] 🔮 Product/Feature Design
- [ ] ✍🏻 Architecture/Implementation Planning
- [ ] 🏗️ Under Construction
- [ ] ⛳ Feature Complete
- [ ] ⛵ GTM / Release

### ✅ To Do

From my fronend app, I want to deploy a contract template from a json definition and initialize a storage

I miss the `asMap `function to create a default MichelsonMap

```
import { address, asMap, int, timestamp } from "../type-aliases";

  const [contract, setContract] =
    useState<PermissionedSimplePollVotingContract>({
      name: "Enter question here ...",
      from_: new Date().toISOString() as timestamp,
      to: new Date().toISOString() as timestamp,
      options: [],
      registeredVoters: [],
      results: asMap<string, int>([]),
      votes: asMap<address, string>([]),
      owner: userAddress as address,
    });
```

Please export all utility function from generated types plugin

thank you !!!

### 📐 Feature Description

see above

super easy to add `export` keyword on each function

### ⚖️ Acceptance Criteria

✨ Features: 
- [ ] ... 
 
 📚 Docs: 
- [ ] ... 

### 🔭 Scope

🏎️ In Scope: 
- ... 
 
 🙅‍♂️ Out of Scope: 
- ... 
 
 

### 🦄 Sizing

1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Great suggestion!
