### ISSUE TITLE
🐛 Bug ➾ Cannot call compile parameters when there is only 1 entrypoint declared

### ISSUE THREAD

**Issue by zamrokk** [pinnacle-labs/taqueria#1903]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Running dapp-1 training , when I try to compile with parameter and new ligo syntax @entry, there is an issue while there is 1 unique entrypoint. If I add a secondary one, no problem. I think it is linked to the fact that in Michelson, when there is only 1 entrypoint, the default naming is overriden to `Default`. Not first time we see this hack :/

![image](https://github.com/pinnacle-labs/taqueria/assets/2536368/65c4dd85-143b-4b41-b06e-df93a11a8e70)

![image](https://github.com/pinnacle-labs/taqueria/assets/2536368/d88f3efe-f87b-410a-a54e-04d8dbf9f81d)

![image](https://github.com/pinnacle-labs/taqueria/assets/2536368/3c04a6ba-6ad8-4aae-bf8d-6bb0e33c4832)

### 🆘 Steps to Reproduce?

Run dapp-1 training here (https://github.com/marigold-dev/training-dapp-1)

try to compile when the parameterList is set before the step of the `taq simulate`

### 🐘 How impactful is this bug?

🤔 Notable but managable

### 💻 Operating System

Windows -> WSL

### 🕸️ System Architecture

None

### 🌮 Taqueria Version

v0.39.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Reproduced. I've reached out to Laurent to see if he can help us figure this one out.

**Comment by mweichert** [comment]
Conversation with LIGO team here: https://tezos-dev.slack.com/archives/CFX0B8Q3X/p1693342733039869

**Comment by mweichert** [comment]
It looks like this is currently expected behavior in LIGO but they are adjusting the implementation so that a single @entry will work as expected with the constructor in place.

**Comment by zamrokk** [comment]
@mweichert 

Some changes are coming to fix this

https://gitlab.com/ligolang/ligo/-/merge_requests/2898#eff41cb129b250b5d2e6507556656d455f615747

We reintroduce the default main entrypoint in case of contract single entrypoint declaration
