### ISSUE TITLE
🐛 Bug ➾ taq test -> cannot find another contract in proxy contract

### ISSUE THREAD

**Issue by mastercodercat** [pinnacle-labs/taqueria#1904]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I wrote two smart contracts using Taqueria. One is for NFT Collection, and the other one is the proxy contract for that collection. I tried to originate two smart contracts using `taq test`, and get addresses of them.

Then, I used those addresses to pass it to proxy contract to call collection contract's method. But I ran into this error `No contract found at this address...`.

Here's a screenshot of the error.

![image](https://github.com/pinnacle-labs/taqueria/assets/91398406/7b9cda76-912f-4fbc-964d-0941cfa86dcb)

Here's code screenshot how I did it.

![image](https://github.com/pinnacle-labs/taqueria/assets/91398406/d0379d31-092a-44a2-9572-502aeb768326)

### 🆘 Steps to Reproduce?

- Create a proxy contract
- Write unit tests with jsligo against that smart contract
- Test it using `taq test` command

### 🐘 How impactful is this bug?

None

### 💻 Operating System

Linux

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

0.39.0

### 🌿 Node.js Version

v16.17.0

### ☎️ Contact Details

smartgeek.taylor@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
@mastercodercat thanks for the report. Do you mind attaching a zip of your project please? It will be easier for us to troubleshoot if we have access to your contracts and the tests you wrote. Thanks again!

**Comment by mweichert** [comment]
@mastercodercat by the looks of it, you're attemping to use the LIGO Test Framework to test and reference address on the main production chain.  If so, that won't work as LIGO Test Framework is to simulate actions like origination and transferring tez. All actions run locally in a simulated environment.

We're actively investigating how Taqueria can handle more complex deployments, such as when one contract has a dependency on another contract. I'll be creating a discussion post for this topic this week.

In the mean time, you could probably write your deployment code using [@taqueria/toolkit](https://github.com/pinnacle-labs/taqueria/tree/main/taqueria-toolkit) and `@taquito/taquito`. Let me know if you go this route and need some help.
