### ISSUE TITLE
🐛 Bug ➾ `taq opt-in` fails with "Path does not exist"

### ISSUE THREAD

**Issue by egarson** [pinnacle-labs/taqueria#1911]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Doing a `taq opt-in` on a fresh install of 0.40.0 results in "Path does not exist: /home/edward/.taq-settings/taq-settings.json".

### 🆘 Steps to Reproduce?

Run `taq opt-in` on a fresh install (I just re-installed the OS, XUbuntu/XFCE4, fwiw).

### 🪵 Relevant log output

```shell
batl git:(master) ✗ taq opt-in
taq opt-in

Opt-in to sharing anonymous usage analytics

Options:
  -p, --projectDir  Path to your project directory                                                                                                                                                                              [default: "./"]
  -e, --env         Specify an environment configuration
      --version     Show version number                                                                                                                                                                                               [boolean]
      --build       Display build information about the current version                                                                                                                                                               [boolean]

Path does not exist: /home/edward/.taq-settings/taq-settings.json
```

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

Every time.

### 💻 Operating System

None

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

0.40.0

### 🌿 Node.js Version

v16.20.0

### ☎️ Contact Details

egarson@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Thanks for the report, @egarson! I'll look into this right away.
