### ISSUE TITLE
🐛 Bug ➾ `taq compile{,-all}` emits superfluous error messages

### ISSUE THREAD

**Issue by egarson** [pinnacle-labs/taqueria#1912]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I followed exactly the steps in the quickstart, just a `taq init`, create the contract files in contracts/, install the ligo plugin, and then `taq compile counter.mligo` or `taq compile-all`. The contract is correctly generated (counter.tz) but error messages are issued. At first I thought it failed, obviously.

### 🆘 Steps to Reproduce?

As above.

### 🪵 Relevant log output

```shell
➜  batl git:(master) ✗ taq compile counter.mligo

=== Error messages for counter.storageList.mligo ===
An internal error ocurred. Please, contact the developers.
Module Contract not found with last Contract.


===

=== Error messages for counter.storageList.mligo ===
An internal error ocurred. Please, contact the developers.
Module Contract not found with last Contract.


===

=== Error messages for counter.parameterList.mligo ===
An internal error ocurred. Please, contact the developers.
Module Contract not found with last Contract.


===
┌───────────────┬──────────────────────────────────────────┐
│ Source        │ Artifact                                 │
├───────────────┼──────────────────────────────────────────┤
│ counter.mligo │ artifacts/counter.tz                     │
│               │ counter.storageList.mligo not compiled   │
│               │ counter.storageList.mligo not compiled   │
│               │ counter.parameterList.mligo not compiled │
└───────────────┴──────────────────────────────────────────┘

Compiled 1 contract(s) in "counter.mligo"
```

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

Every time

### 💻 Operating System

Linux

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

0.40.0

### 🌿 Node.js Version

v16.20.0

### ☎️ Contact Details

egarson@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Hey, thanks for this @egarson! We're working on a total revamp to the documentation, and my best guess is that the documentation is incorrect in some way. But I'll look into this today and should have a fix in no time. Hope all is well with you. :)

**Comment by egarson** [comment]
Sounds great @mweichert , I'm psyched to do some CameLIGO development again, so I'll keep nit-picking 😹

**Comment by mweichert** [comment]
@egarson so I updated the error messaging to be a little bit better, but also, updated the quickstart:
https://fe860a82.taqueria-3ql.pages.dev/docs/getting-started/quickstart/

LIGO has changed quite a bit, and the quickstart was using a form of a contract that is no longer supported. If you don't mind giving the Quickstart another try and letting me know how you make out, that would be wonderful! Thanks again!

**Comment by mweichert** [comment]
@egarson when following the quickstart, you'll need to use the beta version of Taqueria. You can find the binaries at the bottom of this page:
https://github.com/pinnacle-labs/taqueria/actions/runs/6410281940

You'll then need to install the version of the LIGO plugin that has the fix:
`taq install @taqueria/plugin-ligo@0.40.6`
