### ISSUE TITLE
🐛 Bug ➾ Having trouble downloading via homebrew

### ISSUE THREAD

**Issue by Yangobears** [pinnacle-labs/taqueria#1919]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

When I tried to 
`brew install taqueria`
I got 
```
Fetching pinancle-labs/taqueria/taqueria
==> Downloading https://github.com/pinnacle-labs/taqueria/archive/refs/tags/v0.42.00.tar.gz
curl: (22) The requested URL returned error: 404

Error: taqueria: Failed to download resource "taqueria"
Download failed: https://github.com/pinnacle-labs/taqueria/archive/refs/tags/v0.42.00.tar.gz
```

### 🆘 Steps to Reproduce?

`brew tap pinancle-labs/taqueria https://github.com/pinnacle-labs/taqueria`
`brew install taqueria`

### 🪵 Relevant log output

```shell
==> Fetching deno
==> Downloading https://ghcr.io/v2/homebrew/core/deno/manifests/1.37.2
Already downloaded: /Users/yanli/Library/Caches/Homebrew/downloads/0dbea68648d5abaab0b9116fba9be65adc48d2c04e73679856b06913454b602b--deno-1.37.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/deno/blobs/sha256:75b97a80faa5039fbab68598f3539490abd2464c0ffe0b1bdf36582c6959ab9f
Already downloaded: /Users/yanli/Library/Caches/Homebrew/downloads/1a854aed0f451cd2075d25fb4b576891ac0d3bca0b00e88ceec1c882abb22bc6--deno--1.37.2.arm64_ventura.bottle.tar.gz
==> Fetching pinancle-labs/taqueria/taqueria
==> Downloading https://github.com/pinnacle-labs/taqueria/archive/refs/tags/v0.42.00.tar.gz
curl: (22) The requested URL returned error: 404

Error: taqueria: Failed to download resource "taqueria"
```

### 🐘 How impactful is this bug?

🚒 Showstopper

### ⏱️ Prevalance

I cannot download taqueria with this bug 

### 💻 Operating System

MacOS

### 🕸️ System Architecture

arm64 (M1 Macs)

### 🌿 Node.js Version

v18.17.1

### ☎️ Contact Details

yan@blockus.gg

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
@Yangobears thank you so much for adding the issue and we apologize for the mishap. This issue should be fixed. You just need to run `brew install taqueria` again and it should work.
