### ISSUE TITLE
🐛 Bug ➾ Cannot deploy anymore with plugin-taquito v0.43.0

### ISSUE THREAD

**Issue by zamrokk** [pinnacle-labs/taqueria#1925]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

Last version of Taquito plugin fails to deploy contracts

### 🆘 Steps to Reproduce?

It works on v0.42.0
![image](https://github.com/pinnacle-labs/taqueria/assets/2536368/da193ecd-3c02-4744-86e7-d810dc22f786)

It fails on v0.43.0
![image](https://github.com/pinnacle-labs/taqueria/assets/2536368/afb85e3e-75d7-479b-8d2f-5a676c26ae49)

But the taq binary I use is the same v0.43.0, so ti is a Taquito plugin issue

### 🐘 How impactful is this bug?

🚒 Showstopper

### 💻 Operating System

Windows -> WSL

### 🕸️ System Architecture

None

### 🌮 Taqueria Version

0.43.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zamrokk** [comment]
on v0.40.0 (without the plugin-octez-client installed) it works

![image](https://github.com/pinnacle-labs/taqueria/assets/2536368/462b0698-9782-441c-97df-fb5d16049784)

on 0.42.0 (we require the plugin-octez_client at maximimum v0.42.0 to be able to deploy, otherwise it fails)

![image](https://github.com/pinnacle-labs/taqueria/assets/2536368/d8920a94-e8d4-4bda-bbe9-fac4d74c6c98)

**Comment by zamrokk** [comment]
Well, it seems to be related to Docker issue

I restarted the laptop and it deploys now

**Comment by mweichert** [comment]
Interesting. About how long would your flextesa container might have been running?

**Comment by zamrokk** [comment]
I am always using the Ghostnet

Le lun. 13 nov. 2023 à 13:42, Michael Weichert ***@***.***> a
écrit :
