### ISSUE TITLE
🐛 Bug ➾ Variant is not properly defined

### ISSUE THREAD

**Issue by zamrokk** [pinnacle-labs/taqueria#1935]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I generated types using `taq generate`
When I try to display a status field that is a variant type, it did not display, so I debugged it and I found that typing does not match

### 🆘 Steps to Reproduce?

1. use a ligo variant : `export type STATUS = ["ACTIVE"] | ["RECOVERING", address, timestamp] | ["DEAD"];`  on a contract storage

2. deploy this contract with a status RECOVERING

3. generate the types on a dapp and try to display the status + the embedded address and the timestamp. 

Instead of expected field 0 and 1 , the values are stored on fields 3 and 4

![image](https://github.com/pinnacle-labs/taqueria/assets/2536368/808e069b-2f4c-4b64-b412-b7697af08f12)

### 🪵 Relevant log output

```shell
"@taquito/taquito": "^19.2.0",

taqueria   0.50.0

"@taqueria/plugin-contract-types": "^0.50.0",
```

### 🐘 How impactful is this bug?

🤔 Notable but managable

### 💻 Operating System

Windows -> WSL

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

0.50.0

### 🌿 Node.js Version

v18.19.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Closing this, as we determined this to be a bug with Taquito.

**Comment by zamrokk** [comment]
Thank you Michael !
