### ISSUE TITLE
[Bug]: Ligo/Archetype contract compilation error messages will be lost on first compilation due to downloading the docker image

### ISSUE THREAD

**Issue by alexzbusko** [pinnacle-labs/taqueria#979]
### What happened?

If a user wants to compile a contract using either LIGO or Archetype and there are any problems with the initial compilation the error messages will not be shown due to the docker image download happening before the compilation step. This means that the user will not see anything being wrong in the logs they can see since it is just the docker image download logs. This is a generally bad experience and new developers will likely make a mistake and have this happen to them

### What should have happened?

We should either format/segment the long error into multiple messages or compress/replace the docker image download messages with a single message along the lines of "downloading docker image XYZ"

### Steps to reproduce the bug

Steps to reproduce the error:

1. Initialize a taqueria project in vscode
2. Install the ligo plugin
3. Create a file in the contracts directory named "increment.jsligo" with the following content:
```
type storage = int;

type parameter =
| ["Increment", int]
| ["Decrement", int]
| ["Reset"];

type return_ = [list <operation>, storage];

/* Two entrypoints */
let add = ([store, delta] : [storage, int]) : storage => store + delta;
let sub = ([store, delta] : [storage, int]) : storage => store - delta;

/* Main access point that dispatches to the entrypoints according to
   the smart contract parameter. */
let main = ([action, store] : [parameter, storage]) : return_ => {
 return [
   (list([]) as list <operation>),    // No operations
   (match (action, {
    Increment: (n: int) => add ([store, n]),
    Decrement: (n: int) => sub ([store, n]),
    Reset:     ()  => 0}))
  ]
};
```
4. Open the command palette and select the compile ligo command

The popup shows an error occurred but it cannot be seen due to all the docker image download messages

### Screenshots and images

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/29528321/178832775-03a582c2-2fbf-490e-a6df-018ae2684d10.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by russellmorton** [comment]
Hey @mweichert I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/sprint-board-627afc6dad61b0002007f424/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by mweichert** [comment]
Fixed
